<a href="https://colab.research.google.com/github/maheshk9999/My_Projects/blob/main/DS_Major_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
file = "/content/drive/MyDrive/Colab Notebooks/adult (1).csv"

df1 = pd.read_csv(file)
df1.head()

39          State-gov   77516   Bachelors   13        Never-married  \
0  50   Self-emp-not-inc   83311   Bachelors   13   Married-civ-spouse   
1  38            Private  215646     HS-grad    9             Divorced   
2  53            Private  234721        11th    7   Married-civ-spouse   
3  28            Private  338409   Bachelors   13   Married-civ-spouse   
4  37            Private  284582     Masters   14   Married-civ-spouse   

         Adm-clerical   Not-in-family   White     Male   2174   0   40  \
0     Exec-managerial         Husband   White     Male      0   0   13   
1   Handlers-cleaners   Not-in-family   White     Male      0   0   40   
2   Handlers-cleaners         Husband   Black     Male      0   0   40   
3      Prof-specialty            Wife   Black   Female      0   0   40   
4     Exec-managerial            Wife   White   Female      0   0   40   

    United-States   <=50K  
0   United-States   <=50K  
1   United-States   <=50K  
2   United-States   <=50K  
3            Cuba   <=50K  
4   United-States   <=50K

In [ ]:
names = ["Age","Workclass","Fnlwgt","Education","education_num","marital_status","occupation","relationship","race","sex","capital_gain","capital_loss","hours_per_week","native_country","income"]
df1.columns = names

In [ ]:
df1.head()

Age          Workclass  Fnlwgt   Education  education_num  \
0   50   Self-emp-not-inc   83311   Bachelors             13   
1   38            Private  215646     HS-grad              9   
2   53            Private  234721        11th              7   
3   28            Private  338409   Bachelors             13   
4   37            Private  284582     Masters             14   

        marital_status          occupation    relationship    race      sex  \
0   Married-civ-spouse     Exec-managerial         Husband   White     Male   
1             Divorced   Handlers-cleaners   Not-in-family   White     Male   
2   Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
3   Married-civ-spouse      Prof-specialty            Wife   Black   Female   
4   Married-civ-spouse     Exec-managerial            Wife   White   Female   

   capital_gain  capital_loss  hours_per_week  native_country  income  
0             0             0              13   United-States   <=50K  
1             0             0              40   United-States   <=50K  
2             0             0              40   United-States   <=50K  
3             0             0              40            Cuba   <=50K  
4             0             0              40   United-States   <=50K

In [ ]:
df1.isnull().sum()

Age               0
Workclass         0
Fnlwgt            0
Education         0
education_num     0
marital_status    0
occupation        0
relationship      0
race              0
sex               0
capital_gain      0
capital_loss      0
hours_per_week    0
native_country    0
income            0
dtype: int64

In [ ]:
df1.describe()

Age        Fnlwgt  education_num  capital_gain  capital_loss  \
count  32560.000000  3.256000e+04   32560.000000  32560.000000  32560.000000   
mean      38.581634  1.897818e+05      10.080590   1077.615172     87.306511   
std       13.640642  1.055498e+05       2.572709   7385.402999    402.966116   
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000   
25%       28.000000  1.178315e+05       9.000000      0.000000      0.000000   
50%       37.000000  1.783630e+05      10.000000      0.000000      0.000000   
75%       48.000000  2.370545e+05      12.000000      0.000000      0.000000   
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000   

       hours_per_week  
count    32560.000000  
mean        40.437469  
std         12.347618  
min          1.000000  
25%         40.000000  
50%         40.000000  
75%         45.000000  
max         99.000000

In [ ]:
df1.shape

(32560, 15)

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df1['income'] = le.fit_transform(df1['income'])

In [ ]:
df1.dtypes

Age                int64
Workclass         object
Fnlwgt             int64
Education         object
education_num      int64
marital_status    object
occupation        object
relationship      object
race              object
sex               object
capital_gain       int64
capital_loss       int64
hours_per_week     int64
native_country    object
income             int64
dtype: object

In [ ]:
for col in df1.columns:
    if df1[col].dtypes == 'object':
        df1[col] = le.fit_transform(df1[col].astype(str))

In [ ]:
df1.dtypes

Age               int64
Workclass         int64
Fnlwgt            int64
Education         int64
education_num     int64
marital_status    int64
occupation        int64
relationship      int64
race              int64
sex               int64
capital_gain      int64
capital_loss      int64
hours_per_week    int64
native_country    int64
income            int64
dtype: object

In [ ]:
df1.corr()

Age  Workclass    Fnlwgt  Education  education_num  \
Age             1.000000   0.003786 -0.076646  -0.010508       0.036527   
Workclass       0.003786   1.000000 -0.016587   0.023537       0.052015   
Fnlwgt         -0.076646  -0.016587  1.000000  -0.028156      -0.043159   
Education      -0.010508   0.023537 -0.028156   1.000000       0.359172   
education_num   0.036527   0.052015 -0.043159   0.359172       1.000000   
marital_status -0.266292  -0.064798  0.028184  -0.038398      -0.069338   
occupation     -0.020946   0.255004  0.001554  -0.021274       0.109748   
relationship   -0.263698  -0.090449  0.008922  -0.010879      -0.094145   
race            0.028718   0.049720 -0.021278   0.014135       0.031825   
sex             0.088832   0.095942  0.026882  -0.027349       0.012256   
capital_gain    0.077674   0.033828  0.000437   0.030047       0.122627   
capital_loss    0.057775   0.012231 -0.010259   0.016744       0.079932   
hours_per_week  0.068756   0.138974 -0.018770   0.055510       0.148127   
native_country -0.001151  -0.007710 -0.051957   0.064291       0.050831   
income          0.234039   0.051645 -0.009481   0.079311       0.335182   

                marital_status  occupation  relationship      race       sex  \
Age                  -0.266292   -0.020946     -0.263698  0.028718  0.088832   
Workclass            -0.064798    0.255004     -0.090449  0.049720  0.095942   
Fnlwgt                0.028184    0.001554      0.008922 -0.021278  0.026882   
Education            -0.038398   -0.021274     -0.010879  0.014135 -0.027349   
education_num        -0.069338    0.109748     -0.094145  0.031825  0.012256   
marital_status        1.000000   -0.009617      0.185461 -0.068025 -0.129337   
occupation           -0.009617    1.000000     -0.075620  0.006779  0.080328   
relationship          0.185461   -0.075620      1.000000 -0.116052 -0.582453   
race                 -0.068025    0.006779     -0.116052  1.000000  0.087197   
sex                  -0.129337    0.080328     -0.582453  0.087197  1.000000   
capital_gain         -0.043398    0.025511     -0.057918  0.011143  0.048477   
capital_loss         -0.034182    0.017979     -0.061064  0.018902  0.045572   
hours_per_week       -0.190521    0.080384     -0.248975  0.041910  0.229312   
native_country       -0.023827   -0.012532     -0.005504  0.137849 -0.008125   
income               -0.199295    0.075448     -0.250924  0.071853  0.215995   

                capital_gain  capital_loss  hours_per_week  native_country  \
Age                 0.077674      0.057775        0.068756       -0.001151   
Workclass           0.033828      0.012231        0.138974       -0.007710   
Fnlwgt              0.000437     -0.010259       -0.018770       -0.051957   
Education           0.030047      0.016744        0.055510        0.064291   
education_num       0.122627      0.079932        0.148127        0.050831   
marital_status     -0.043398     -0.034182       -0.190521       -0.023827   
occupation          0.025511      0.017979        0.080384       -0.012532   
relationship       -0.057918     -0.061064       -0.248975       -0.005504   
race                0.011143      0.018902        0.041910        0.137849   
sex                 0.048477      0.045572        0.229312       -0.008125   
capital_gain        1.000000     -0.031614        0.078409       -0.001984   
capital_loss       -0.031614      1.000000        0.054256        0.000420   
hours_per_week      0.078409      0.054256        1.000000       -0.002671   
native_country     -0.001984      0.000420       -0.002671        1.000000   
income              0.223333      0.150523        0.229690        0.015845   

                  income  
Age             0.234039  
Workclass       0.051645  
Fnlwgt         -0.009481  
Education       0.079311  
education_num   0.335182  
marital_status -0.199295  
occupation      0.075448  
relationship   -0.250924  
race            0.071853  
sex             0.21

In [ ]:
df2 = df1.drop(["Fnlwgt","Education","marital_status","relationship","native_country"],axis=1)
df2

Age  Workclass  education_num  occupation  race  sex  capital_gain  \
0       50          6             13           4     4    1             0   
1       38          4              9           6     4    1             0   
2       53          4              7           6     2    1             0   
3       28          4             13          10     2    0             0   
4       37          4             14           4     4    0             0   
...    ...        ...            ...         ...   ...  ...           ...   
32555   27          4             12          13     4    0             0   
32556   40          4              9           7     4    1             0   
32557   58          4              9           1     4    0             0   
32558   22          4              9           1     4    1             0   
32559   52          5              9           4     4    0         15024   

       capital_loss  hours_per_week  income  
0                 0              13       0  
1                 0              40       0  
2                 0              40       0  
3                 0              40       0  
4                 0              40       0  
...             ...             ...     ...  
32555             0              38       0  
32556             0              40       1  
32557             0              40       0  
32558             0              20       0  
32559             0              40       1  

[32560 rows x 10 columns]

In [ ]:
x = df2.drop(["income"],axis=1)
y = df2.income

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)

In [ ]:
x_train.dtypes

Age               int64
Workclass         int64
education_num     int64
occupation        int64
race              int64
sex               int64
capital_gain      int64
capital_loss      int64
hours_per_week    int64
dtype: object

In [ ]:
print("x_train shape:", x_train.shape)
print("x_test shape:", x_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

x_train shape: (22792, 9)
x_test shape: (9768, 9)
y_train shape: (22792,)
y_test shape: (9768,)


In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import mean_squared_error


In [ ]:
from sklearn.metrics import confusion_matrix,classification_report

####1) Gaussian Naive Bayes Classifier


In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
gnb = GaussianNB()
m_gnb = gnb.fit(x_train, y_train)
y_pred_gnb = gnb.predict(x_test)
y_pred_gnb

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
print('Training acc',m_gnb.score(x_train,y_train))
print('Testing acc',m_gnb.score(x_test,y_test))

Training acc 0.796990171990172
Testing acc 0.7958640458640459


In [ ]:
cm_gnb = confusion_matrix(y_test,y_pred_gnb)
print(cm_gnb)
print(classification_report(y_test,y_pred_gnb))

[[7081  366]
 [1628  693]]
              precision    recall  f1-score   support

           0       0.81      0.95      0.88      7447
           1       0.65      0.30      0.41      2321

    accuracy                           0.80      9768
   macro avg       0.73      0.62      0.64      9768
weighted avg       0.78      0.80      0.77      9768



####2)Decision Tree

In [ ]:
from sklearn.tree import DecisionTreeClassifier

In [ ]:
m_dt = DecisionTreeClassifier(criterion='entropy')

m_dt.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy')

In [ ]:
print('Training acc',m_dt.score(x_train,y_train))
print('Testing acc',m_dt.score(x_test,y_test))

Training acc 0.9656458406458407
Testing acc 0.7997542997542998


In [ ]:
ypred_dt = m_dt.predict(x_test)
print(ypred_dt)

[0 1 0 ... 1 0 0]


In [ ]:
cm_dt = confusion_matrix(y_test,ypred_dt)
print(cm_dt)
print(classification_report(y_test,ypred_dt))

[[6534  913]
 [1043 1278]]
              precision    recall  f1-score   support

           0       0.86      0.88      0.87      7447
           1       0.58      0.55      0.57      2321

    accuracy                           0.80      9768
   macro avg       0.72      0.71      0.72      9768
weighted avg       0.80      0.80      0.80      9768



####3)Random Forest Classifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
m_rf = RandomForestClassifier(n_estimators=100,criterion='entropy',max_depth=7)
m_rf.fit(x_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=7)

In [ ]:
print('Training acc',m_rf.score(x_train,y_train))
print('Testing acc',m_rf.score(x_test,y_test))

Training acc 0.844024219024219
Testing acc 0.8426494676494677


In [ ]:
ypred_rf = m_rf.predict(x_test)
print(ypred_rf)

[0 0 0 ... 1 0 0]


In [ ]:
cm_rf = confusion_matrix(y_test,ypred_rf)
print(cm_rf)
print(classification_report(y_test,ypred_rf))

[[7201  246]
 [1291 1030]]
              precision    recall  f1-score   support

           0       0.85      0.97      0.90      7447
           1       0.81      0.44      0.57      2321

    accuracy                           0.84      9768
   macro avg       0.83      0.71      0.74      9768
weighted avg       0.84      0.84      0.82      9768



####4)Logistic Regression

In [ ]:
from sklearn.linear_model import LogisticRegression

In [ ]:
m_lr = LogisticRegression()
m_lr.fit(x_train,y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression()

In [ ]:
y_pred_lr = lr.predict(x_test)
y_pred_lr

array([0, 0, 0, ..., 0, 0, 0])

In [ ]:
print('Training acc',m_lr.score(x_train,y_train))
print('Testing acc',m_lr.score(x_test,y_test))

Training acc 0.7936117936117936
Testing acc 0.7954545454545454


In [ ]:
cm_lr = confusion_matrix(y_test,y_pred_lr)
print(cm_lr)

[[7151  296]
 [1702  619]]


In [ ]:
print(classification_report(y_test,y_pred_lr))

              precision    recall  f1-score   support

           0       0.81      0.96      0.88      7447
           1       0.68      0.27      0.38      2321

    accuracy                           0.80      9768
   macro avg       0.74      0.61      0.63      9768
weighted avg       0.78      0.80      0.76      9768



####5)KNN Classifiers

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
m_knn = KNeighborsClassifier(n_neighbors=21)
m_knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=21)

In [ ]:
print('Training acc',m_knn.score(x_train,y_train))
print('Testing acc',m_knn.score(x_test,y_test))

Training acc 0.8522288522288523
Testing acc 0.8378378378378378


In [ ]:
ypred_knn = m_knn.predict(x_test)
print(ypred_knn)

[0 1 0 ... 1 0 0]


In [ ]:
cm_knn = confusion_matrix(y_test,ypred_knn)
print(cm_knn)
print(classification_report(y_test,ypred_knn))

[[6989  458]
 [1126 1195]]
              precision    recall  f1-score   support

           0       0.86      0.94      0.90      7447
           1       0.72      0.51      0.60      2321

    accuracy                           0.84      9768
   macro avg       0.79      0.73      0.75      9768
weighted avg       0.83      0.84      0.83      9768

